openapi: 3.0.0
info:
  title: Manager distribution system (Workflow)
  description: Workflow's OpenAPI
servers:
  - url: 'http://localhost:8080'
    description: local
paths: null
components:
  schemas:
    workflow:
      type: object
      required:
        - id
        - name
        - status
        - nodes
        - edges
        - createdAt
        - updatedAt
        - updateAuthor
      properties:
        id:
          type: string
          description: Id воркфлоу
        name:
          type: string
          description: Имя воркфлоу
        status:
          $ref: '#/components/schemas/status'
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/node'
        edges:
          type: array
          items:
            $ref: '#/components/schemas/edge'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        archivedAt:
          type: string
          format: date-time
        updateAuthor:
          $ref: '#/components/schemas/author'
    action:
      type: object
      properties:
        actionType:
          type: string
          enum:
            - assignTeamAction
            - assignManager
            - assignTheme
            - addTag
            - sendMessage
            - sendNote
            - setPriority
            - addClients
        data:
          $ref: '#/components/schemas/actionData'
    actionData:
      type: object
      required:
        - values
      properties:
        values:
          type: array
          items:
            type: string
    author:
      type: object
      required:
        - firstName
        - lastName
        - surname
        - avatar
      properties:
        firstName:
          type: string
        lastName:
          type: string
        surname:
          type: string
        avatar:
          $ref: '#/components/schemas/avatar'
    avatar:
      type: object
      required:
        - url
        - size
        - fileKey
        - fileName
        - mimeType
      properties:
        url:
          type: string
        size:
          type: integer
        fileKey:
          type: string
        fileName:
          type: string
        mimeType:
          type: string
    condition:
      type: object
      required:
        - operator
        - predicates
      properties:
        operator:
          type: string
          enum:
            - or
            - and
        predicates:
          type: array
          items:
            $ref: '#/components/schemas/predicate'
    conditionGroup:
      type: object
      required:
        - operator
        - conditions
      properties:
        operator:
          type: string
          enum:
            - or
            - and
        conditions:
          type: array
          items:
            $ref: '#/components/schemas/condition'
    edge:
      type: object
      required:
        - id
        - source
        - target
      properties:
        id:
          type: string
        source:
          type: string
        target:
          type: string
    node:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
        type:
          type: string
          enum:
            - ActionNode
            - PredicateNode
            - ConditionNode
        data:
          x-go-type: 'interface{}'
          oneOf:
            - $ref: '#/components/schemas/action'
            - $ref: '#/components/schemas/predicate'
            - $ref: '#/components/schemas/conditionGroup'
        position:
          type: object
          required:
            - x
            - 'y'
          properties:
            x:
              type: number
              format: double
            'y':
              type: number
              format: double
    predicate:
      type: object
      required:
        - values
      properties:
        attribute:
          type: string
          enum:
            - companyId
            - clientEmail
            - statusClient
            - text
            - userAgent
            - messageCreatedAt
            - themeId
          description: 'Поле, по которому будет проводится проверка'
        comparison:
          type: string
          enum:
            - Eq
            - NotEq
            - Contains
            - NotContains
            - InInterval
            - NotInInterval
            - EndsWith
            - All
            - Date
          description: 'Выражение для сравнения (eq, contains, not_contains, in_interval, not_in_interval, ends_with, all)'
        values:
          type: array
          items:
            type: string
          description: 'Значения, которые нужно сравнить'
    status:
      type: string
      enum:
        - live
        - paused
        - archived
