type: object
properties:
  actionType:
    type: string
    enum:
      - assignTeamAction
      - assignManager
      - assignTheme
      - addTag
      - sendMessage
      - sendNote
      - setPriority
      - addClients
  data:
    $ref: "./actionData.yaml"
