type: object
required: [id, name, status, nodes, edges, createdAt, updatedAt, updateAuthor]
properties:
  id:
    type: string
    description: Id воркфлоу
  name:
    type: string
    description: Имя воркфлоу
  status:
    $ref: "./status.yaml"
  nodes:
    type: array
    items:
      $ref: "./node.yaml"
  edges:
    type: array
    items:
      $ref: "./edge.yaml"
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
  archivedAt:
    type: string
    format: date-time
  updateAuthor:
    $ref: "./author.yaml"
